"""instance/config.py
"""

from instance.postgresql import SQLALCHEMY_DATABASE_URI as DATABASE_URI

DEBUG = True
# SECRET_KEY is generated by os.urandom(24).
SECRET_KEY = '\xf7\xf4\x9bb\xd7\xa8\xdb\xee\x9f\xe3\x98SR\xda\xb0@\xb7\x12\xa4uB\xda\xa3\x1b'
STRIPE_API_KEY = ''

SQLALCHEMY_DATABASE_URI = DATABASE_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = True
